server:
  port: 8081

spring:
  application:
    name: discord-server-resource-server
  liquibase:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: postgres
    password: postgres
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
org:
  innotice:
    security:
      internalSecret: ${INNOTICE_SECRET_HEADER}

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
