org:
  innotice:
    security:
      secretHeader: ${INNOTICE_SECRET_HEADER}
    client:
      discord:
        bot:
          token: ${DISCORD_BOT_TOKEN}

spring:
  application:
    name: discord-client

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}

server:
  port: 8080