FROM amazoncorretto:17
COPY target/discord-server-resource-server-0.0.1-SNAPSHOT.jar discord-server-resource-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","discord-server-resource-server-0.0.1-SNAPSHOT.jar"]